### ISSUE TITLE
rerunning python saw scripts generates errors

### ISSUE THREAD

**Issue by pnwamk** [GaloisInc/galois-py-toolkit#5]
Steps:
```
$ .../saw-remote-api http --host 0.0.0.0 --port 8080 / &

$ export SAW_SERVER_URL="http://localhost:8080/"

$ python3 tests/saw/test_salsa20_easy.py 
✅  Verified: lemma_RotlContract (defined at /Users/andrew/Repos/GRINDSTONE/galois-py-toolkit/tests/saw/test_salsa20_easy.py:139)
✅  Verified: lemma_QuarterRoundContract (defined at /Users/andrew/Repos/GRINDSTONE/galois-py-toolkit/tests/saw/test_salsa20_easy.py:141)
✅  Verified: lemma_RowRoundContract (defined at /Users/andrew/Repos/GRINDSTONE/galois-py-toolkit/tests/saw/test_salsa20_easy.py:143)
✅  Verified: lemma_ColumnRoundContract (defined at /Users/andrew/Repos/GRINDSTONE/galois-py-toolkit/tests/saw/test_salsa20_easy.py:145)
✅  Verified: lemma_DoubleRoundContract (defined at /Users/andrew/Repos/GRINDSTONE/galois-py-toolkit/tests/saw/test_salsa20_easy.py:147)
✅  Verified: lemma_HashContract (defined at /Users/andrew/Repos/GRINDSTONE/galois-py-toolkit/tests/saw/test_salsa20_easy.py:149)
✅  Verified: lemma_ExpandContract (defined at /Users/andrew/Repos/GRINDSTONE/galois-py-toolkit/tests/saw/test_salsa20_easy.py:151)
✅  Verified: lemma_Salsa20CryptContract (defined at /Users/andrew/Repos/GRINDSTONE/galois-py-toolkit/tests/saw/test_salsa20_easy.py:112)
.
----------------------------------------------------------------------
Ran 1 test in 2.818s

OK
✅  All verified!

$ python3 tests/saw/test_salsa20_easy.py
E
======================================================================
ERROR: test_salsa20 (__main__.Salsa20EasyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/andrew/Repos/GRINDSTONE/galois-py-toolkit/tests/saw/test_salsa20_easy.py", line 137, in test_salsa20
    mod = llvm_load_module(bcname)
  File "/Users/andrew/Repos/GRINDSTONE/galois-py-toolkit/saw/__init__.py", line 303, in llvm_load_module
    __get_designated_connection().llvm_load_module(name, bitcode_file).result()
  File "/Users/andrew/Repos/GRINDSTONE/galois-py-toolkit/saw/connection.py", line 112, in llvm_load_module
    self.most_recent_result = LLVMLoadModule(self, name, bitcode_file)
  File "/Users/andrew/Repos/GRINDSTONE/galois-py-toolkit/saw/commands.py", line 36, in __init__
    super(LLVMLoadModule, self).__init__(
  File "/usr/local/lib/python3.9/site-packages/argo_client/interaction.py", line 57, in __init__
    self.init_state = connection.protocol_state()
  File "/Users/andrew/Repos/GRINDSTONE/galois-py-toolkit/saw/connection.py", line 104, in protocol_state
    return self.most_recent_result.state()
  File "/usr/local/lib/python3.9/site-packages/argo_client/interaction.py", line 159, in state
    return self._result_and_state_and_out_err()[1]
  File "/usr/local/lib/python3.9/site-packages/argo_client/interaction.py", line 148, in _result_and_state_and_out_err
    raise self.process_error(exception)
saw.exceptions.CryptolError: error: Attempted to register the following name twice: cryptol:/Salsa20/quarterround

----------------------------------------------------------------------
Ran 1 test in 0.074s

FAILED (errors=1)
✅  All verified!
```

Originally reported here: https://github.com/GaloisInc/saw-script/issues/1055

**Comment by pnwamk** [comment]
Some initial investigation: the initial [SAWState](https://github.com/GaloisInc/saw-script/blob/31d691b1d599a928e7862ed5f5a52c0c161853d6/saw-remote-api/src/SAWServer.hs#L160) for the `saw-remote-api` server contains a SAWCore [SharedContext](https://github.com/GaloisInc/saw-core/blob/bf92e92cb0529e3425121a7b179f24b8a71f6593/saw-core/src/Verifier/SAW/SharedTerm.hs#L333), which contains mutable references for tracking and storing the state of SAW. That seems to be the underlying "why" of the issue here: even if you start a request from the "initial server state", that initial state has changed if someone else has come before you.

**Comment by pnwamk** [comment]
The following merged PRs/commits should resolve this issue:

https://github.com/GaloisInc/argo/pull/155
https://github.com/GaloisInc/cryptol/pull/1095
https://github.com/GaloisInc/saw-script/commit/96eb69ff80ae852729fe22bc0e8d7cd474ad5f3a
https://github.com/GaloisInc/saw-script/pull/1118
